# Generated by Django 2.2.7 on 2019-12-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bathroooms',
            new_name='bathrooms',
        ),
    ]
